name: stack-grafana_argon

services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    user: "0:0"
    command: -config.file=/etc/loki/config.yaml
    ports:
      - "3100:3100"
    restart: unless-stopped
    volumes:
      - ./loki-config.yaml:/etc/loki/config.yaml:ro
      - ${DOCKERDATADIR}/loki:/loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "472:472"
    dns_search:
      - fdatxvault.win
    env_file:
      - secrets-influxdb.env
    environment:
      PGID: "${PGID}"
      PUID: "${PUID}"
      TZ: "${TZ}"
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ${DOCKERDATADIR}/grafana:/var/lib/grafana
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources:ro

  influxdb:
    image: influxdb:2
    container_name: influxdb
    env_file: secrets-influxdb.env
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
    ports:
      - "8086:8086"
    restart: unless-stopped
    volumes:
      - ${DOCKERDATADIR}/influxdb:/var/lib/influxdb2
