title: "Home Lab Dashboard"
theme: dark
background:
  image: https://assets.science.nasa.gov/dynamicimage/assets/science/missions/webb/science/2025/07/STScI-01JY2AYZ2PYBDDSMX83K5248DD.jpg?w=11055&h=12138&fit=crop&crop=faces%2Cfocalpoint
  opacity: 15

navbar:
  links: []

useEqualHeights: true

layout:
  - Health:
      tab: Default
  - Devices:
      tab: Default
  - Proxmox:
      tab: Default
  - Other:
      tab: Default
  - Web:
      tab: Default
  - Media:
      tab: Media
  - Torrenting:
      tab: Media
  - Movies and TV Shows:
      tab: Media
  - System Monitoring:
      columns: 4
      style: row
      tab: Monitoring
  - Metrics & Analytics:
      tab: Monitoring
  - Infrastructure Monitoring:
      tab: Monitoring
  - AI:
      tab: AI