name: stack-openwebui_argon

services:
  db:
    image: postgres:16
    restart: unless-stopped
    container_name: litellm_db
    env_file:
      - app.env
    environment:
      POSTGRES_DB: litellm
      POSTGRES_USER: llmproxy
    ports:
      - "5432:5432"
    volumes:
      - ${DOCKERDATADIR}/open-webui/data:/var/lib/postgresql/data # Persists Postgres data across container restarts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d litellm -U llmproxy"]
      interval: 1s
      timeout: 5s
      retries: 10

  litellm:
    container_name: litellm
    image: ghcr.io/berriai/litellm:main-latest
    env_file:
      - app.env
    environment:
      - TZ=${TZ}
      - PORT=4000
      - SEARXNG_API_BASE=http://searxng:8080
    ports:
      - "4000:4000"
    restart: unless-stopped
    volumes:
      - ./litellm-config.yaml:/app/config.yaml
      # - ${DOCKERDATADIR}/litellm/config:/app/config
    command: ["--config", "/app/config.yaml", "--port", "4000", "--num_workers", "1"]
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; exit(0) if urllib.request.urlopen('http://localhost:4000/health/liveliness').getcode() == 200 else exit(1)\""]
      interval: 10s
      timeout: 5s
      retries: 5

  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:ollama
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - WEBUI_AUTH="True"
    ports:
      - "3001:8080"
    restart: unless-stopped
    volumes:
      - ${DOCKERDATADIR}/open-webui/ollama:/root/.ollama
      - ${DOCKERDATADIR}/open-webui/data:/app/backend/data

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped
    ports:
      - 8888:8080
    volumes:
      - ./searxng:/etc/searxng:rw
    env_file:
      - app.env
    environment:
      - SEARXNG_BASE_URL=http://argon:8888/
      - TZ=${TZ}

  mcpo:
    image: ghcr.io/open-webui/mcpo:main
    container_name: mcpo
    restart: unless-stopped
    ports:
      - "8001:8000"
    env_file:
      - mcpo.env
    volumes:
      - ./mcpo-config.json:/app/config.json:ro
      - ${DOCKERDATADIR}/open-webui/joplin-mcp-server:/jdata
    command: ["--config", "/app/config.json", "--hot-reload"]
    depends_on:
      - open-webui
