services:
  unifi-db:
    container_name: unifi-db
    image: docker.io/mongo:8
    env_file:
      - secrets.env
    restart: unless-stopped
    volumes:
      - ${DOCKERDATADIR}/unifinetwork/db:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro

  unifi-network-application:
    container_name: unifi-network-application
    image: lscr.io/linuxserver/unifi-network-application:latest
    env_file:
      - secrets.env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
      - MONGO_TLS= #optional
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8087:8087
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped
    volumes:
      - ${DOCKERDATADIR}/unifinetwork/config:/config